version: '3.8'
services:
  postgres:
    container_name: postgres-db
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=yoyo
      - POSTGRES_PASSWORD=5555
      - POSTGRES_DB=echo-hex
    networks:
      - Heepoke
  redis:
    image: "redis:latest"
    container_name: redis
    hostname: redis
    command: ["redis-server", "--include", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      - "./redis/redis.conf:/usr/local/etc/redis/redis.conf"
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - Heepoke

networks:
  Heepoke:
    driver: bridge
