version: '3.8'
services:
  postgres:
    container_name: postgres-db
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=yoyo
      - POSTGRES_PASSWORD=5555
      - POSTGRES_DB=echo-hex
    networks:
      - Heepoke
  redis:
    image: redis:latest
    container_name: redis-cache
    hostname: redis
    command: ["redis-server", "--include", "/usr/local/etc/redis/redis.conf", "--appendonly", "yes", "--requirepass", "yoyo5555"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/var/lib/redis
      - "./pkg/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf"
    environment:
      REDIS_REPLICATION_MODE: master
      REDIS_PASSWORD: 
    networks:
      - Heepoke
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: echo-api
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 6476:6476
    depends_on:
      - postgres
      - redis
    networks:
      - Heepoke

volumes:
  redis-data:

networks:
  Heepoke:
    driver: bridge
